name: pull_request

on:
  pull_request:
    branches:
      - master
      - 1.9.x
      - 1.8.x
      - 1.7.x
      - 1.6.x
      - 1.5.x
      - 1.4.x
      - 1.3.x
      - 1.2.x
      - 1.1.x
      - 1.0.x

jobs:
  node:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [20, 21]

    steps:
      - uses: actions/checkout@v4

      - name: node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: installing
        run: npm ci

      - name: setup
        run: npm run setup

      - name: testing wasm
        run: npm run test:rs -- --node

      - name: building
        run: npm run build

      - name: testing builded files
        run: npm run test:ts
